# docker-compose.deploy.yml
version: '0.1'

networks:
  micro_network:
    name: micro_network
    external: True

services:
  web-app:
    container_name: web-app
    image: sema-web-app:latest
    command: python3 application/SemaServer.py 
    build:
      context: .
      dockerfile: ./sema_web_app/Dockerfile
    ports:
    - "5000:5000"
    restart: always
    volumes:
      - ${PWD}/sema_web_app/:/sema-web-app
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=unix$DISPLAY
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_RUN_HOST=
    networks:
      - micro_network # TODO set fix IPv4 ?
  
  sema-scdg:
    container_name: sema-scdg
    image: sema-scdg:latest
    command: python3 SCDGApp.py
    build:
      context: .
      dockerfile: ./sema_scdg/Dockerfile
    ports:
    - "5001:5001"
    restart: always
    volumes:
      - ${PWD}/sema_scdg/:/sema-scdg 
      - ${PWD}/submodules/angr-utils:/sema-scdg/application/submodules/angr-utils 
      - ${PWD}/submodules/bingraphvis:/sema-scdg/application/submodules/bingraphvis 
      - ${PWD}/penv-fix/:/sema-scdg/application/penv-fix 
      - ${PWD}/database/:/sema-scdg/application/database
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=unix$DISPLAY
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_RUN_HOST=
    networks:
      - micro_network # TODO set fix IPv4 ?

  sema-classifier:
    container_name: sema-classifier
    image: sema-classifier:latest
    build:
      context: .
      dockerfile: ./sema_classifier/Dockerfile
    ports:
      - "5002:5002"
    restart: always
    networks:
      - micro_network
