# docker-compose.deploy.yml
version: '0.1'

services:
  web-app:
    image: sema-web-app:latest
    build:
      context: .
    ports:
    - "5000:5000"
    restart: always
  
  SemaSCDG:
    image: sema-scdg:latest
    build:
      context: ..
      dockerfile: ./SemaSCDG/Dockerfile
    ports:
    - "5001:5001"
    restart: always