# docker-compose.deploy.yml
version: '0.1'

networks:
  micro_network:
    external:
      name: micro_network

services:
  frontend-app:
    container_name: web-app
    build:
      context: .
    ports:
    - "5000:5000"
    networks:
    - micro_network
    restart: always

  SemaSCDG:
    container_name: SemaSCDG
    build:
      context: .
    ports:
    - "5001:5001"
    networks:
    - micro_network
    restart: always