# docker-compose.deploy.yml
version: '0.1'

networks:
  micro_network:
    name: micro_network
    external: True

services:
  web-app:
    container_name: web-app
    image: sema-web-app:latest
    build:
      context: .
    ports:
    - "5000:5000"
    depends_on:
      - sema-scdg
    restart: always
  
  sema-scdg:
    container_name: sema-scdg
    image: sema-scdg:latest
    build:
      context: ..
      dockerfile: ./SemaSCDG/Dockerfile
    ports:
    - "5001:5001"
    restart: always