# docker-compose.yml
version: '2'


networks:
  micro_network:
    name: micro_network
    external: True

services:
  sema-scdg:
    container_name: sema-scdg
    image: sema-scdg:latest
    command: python3 SCDGApp.py config.ini
    build:
      context: .
      dockerfile: ./sema_scdg/Dockerfile
    ports:
    - "5001:5001"
    restart: always
    volumes:
      - ${PWD}/sema_scdg/:/sema-scdg 
      - ${PWD}/submodules/angr-utils:/sema-scdg/application/submodules/angr-utils 
      - ${PWD}/submodules/bingraphvis:/sema-scdg/application/submodules/bingraphvis 
      - ${PWD}/penv-fix/:/sema-scdg/application/penv-fix 
      - ${PWD}/database/:/sema-scdg/application/database
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=unix$DISPLAY
    networks:
      - micro_network # TODO set fix IPv4 ?

      

  